# FROM nexus-container-registry-nexus.apps.cluster-3bcb.sandbox1869.opentlc.com/fuse7/fuse-java-openshift:latest
FROM nexus-container-registry-global-pull-nexus.apps.cluster-3bcb.sandbox1869.opentlc.com/fuse7/fuse-java-openshift:latest

COPY *.jar /deployments