= Overview 

This repository contains resources needed for the CI/CD process for the https://github.com/workload-assessment-openshift4/springboot-camel-example[springboot-camel-example] Java application.

To deploy the application to Openshift you will need to run the build and deployment pipelines. Navigate to the appropriate subdirectory for instructions on how to do so.

== Helm chart

The Helm chart will be used to deploy the application in an OpenShift namespace. It creates the required resources:

* Deployment
* Service
* Route
* ConfigMaps
* Secrets
* ServiceAccount

== Container image

These files will be used to create an image that will be used in the deployment pipeline.  It is created from a base image with Java 8 installed. 

The build pipeline will create the WAR file that is referenced in the Dockerfile.

== Pipelines

There are two pipelines: build and deploy. 

The build pipeline creates a WAR artifact via Maven. Buildah will then create a new image with the https://github.com/workload-assessment-openshift4/springboot-camel-example-cicd/tree/master/container-image[Dockerfile] and push it to a nexus image registry.

The deploy pipeline utilizes Helm to create all the necessary resources to run the application. It will use the image that was created by the build pipeline as the image for the deployed application.