apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-camel-example-chart.fullname" . }}
  labels:
    {{- include "springboot-camel-example-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "springboot-camel-example-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "springboot-camel-example-chart.selectorLabels" . | nindent 8 }}
        deploytime: {{ now }}
    spec:
      {{- if or .Values.imagePullSecrets .Values.imageCredentials }}
      imagePullSecrets:
        {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.imageCredentials }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "springboot-camel-example-chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: 8778-tcp
              containerPort: 8778
              protocol: TCP
            - name: 9779-tcp
              containerPort: 9779
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.handlerPath }}
              port: http
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.handlerPath }}
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
           - name: spring.config.additional-location
             value: file:/etc/configmaps/{{ include "springboot-camel-example-chart.fullname" . }}/
          envFrom:
            - configMapRef:
                name: {{ include "springboot-camel-example-chart.fullname" . }}
                optional: true
          volumeMounts:
          - mountPath: /etc/configmaps/{{ include "springboot-camel-example-chart.fullname" . }}
            name: volume-cm
      volumes:
        - name: volume-cm
          configMap:
            defaultMode: 420
            name: {{ include "springboot-camel-example-chart.fullname" . }}-mount
            optional: true